name: grocery_app
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.6.0
  shared_preferences: ^2.2.2
  carousel_slider: ^5.0.0
  razorpay_flutter: ^1.3.7  # <--- ADD THIS LINE HERE

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1  # <--- Now it is correctly placed here!

flutter:
  uses-material-design: true

# --- Icon Configuration ---
flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon.png"